application: questions-and-answers
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: QuestionsApp.wsgi.application 

libraries:

- name: django
  version: "latest"
  
- name: MySQLdb
  version: "latest"
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'QuestionsApp.settings'